### ISSUE TITLE
Altar Crafting crash

### ISSUE THREAD

**Issue by bofrankbo** [Torchrism/Torchrism-Mod#2]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 8/25/20 9:33 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at com.atomuze.torchrism.block.torch_altar.tileEntity.TileEntityMainPedestal.extractItem(TileEntityMainPedestal.java:96)
	at com.atomuze.torchrism.block.torch_altar.tileEntity.TileEntityMainPedestal.craftingEffect(TileEntityMainPedestal.java:75)
	at com.atomuze.torchrism.block.torch_altar.tileEntity.TileEntityMainPedestal.func_73660_a(TileEntityMainPedestal.java:54)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.atomuze.torchrism.block.torch_altar.tileEntity.TileEntityMainPedestal.extractItem(TileEntityMainPedestal.java:96)
	at com.atomuze.torchrism.block.torch_altar.tileEntity.TileEntityMainPedestal.craftingEffect(TileEntityMainPedestal.java:75)
	at com.atomuze.torchrism.block.torch_altar.tileEntity.TileEntityMainPedestal.func_73660_a(TileEntityMainPedestal.java:54)

-- Block entity being ticked --
Details:
	Name: torchrism:altar_main_pedestal // com.atomuze.torchrism.block.torch_altar.tileEntity.TileEntityMainPedestal
	Block type: ID #277 (tile.torchrism.altar_main_pedestal_night // com.atomuze.torchrism.block.torch_altar.block.BlockAltarMainPedestal // torchrism:altar_main_pedestal_night)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (1574,4,1075), Chunk: (at 6,0,3 in 98,67; contains blocks 1568,0,1072 to 1583,255,1087), Region: (3,2; contains chunks 96,64 to 127,95, blocks 1536,0,1024 to 2047,255,1535)
	Actual block type: ID #277 (tile.torchrism.altar_main_pedestal_night // com.atomuze.torchrism.block.torch_altar.block.BlockAltarMainPedestal // torchrism:altar_main_pedestal_night)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Dexmio'/107, l='MpServer', x=1594.80, y=30.71, z=1085.47]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (1547,4,1051), Chunk: (at 11,0,11 in 96,65; contains blocks 1536,0,1040 to 1551,255,1055), Region: (3,2; contains chunks 96,64 to 127,95, blocks 1536,0,1024 to 2047,255,1535)
	Level time: 527978 game time, 12001 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 21 total; [EntityCow['Cow'/66, l='MpServer', x=1538.38, y=4.00, z=1161.20], EntityItem['item.tile.torch'/67, l='MpServer', x=1561.17, y=4.00, z=1066.76], EntityPlayerSP['Dexmio'/107, l='MpServer', x=1594.80, y=30.71, z=1085.47], EntityItem['item.tile.torch'/70, l='MpServer', x=1572.44, y=4.00, z=1067.63], EntityItem['item.tile.torch'/71, l='MpServer', x=1568.60, y=4.00, z=1060.26], EntityHorse['Horse'/74, l='MpServer', x=1573.04, y=4.00, z=1111.13], EntityCow['Cow'/76, l='MpServer', x=1591.55, y=4.00, z=1120.78], EntitySheep['Sheep'/77, l='MpServer', x=1588.71, y=4.00, z=1123.79], EntitySheep['Sheep'/78, l='MpServer', x=1587.85, y=4.00, z=1138.16], EntitySheep['Sheep'/79, l='MpServer', x=1598.25, y=4.00, z=1163.23], EntitySheep['Sheep'/80, l='MpServer', x=1599.74, y=4.00, z=1162.23], EntityHorse['Horse'/82, l='MpServer', x=1621.48, y=4.00, z=1099.17], EntitySheep['Sheep'/83, l='MpServer', x=1612.15, y=4.00, z=1130.21], EntitySheep['Sheep'/84, l='MpServer', x=1603.17, y=4.00, z=1136.19], EntitySheep['Sheep'/85, l='MpServer', x=1606.81, y=4.00, z=1156.40], EntityHorse['Horse'/86, l='MpServer', x=1602.18, y=4.00, z=1152.04], EntitySheep['Sheep'/55, l='MpServer', x=1522.84, y=4.00, z=1099.84], EntitySheep['Sheep'/56, l='MpServer', x=1520.29, y=4.00, z=1133.56], EntitySheep['Sheep'/88, l='MpServer', x=1631.69, y=4.00, z=1006.82], EntitySheep['Sheep'/57, l='MpServer', x=1524.28, y=4.00, z=1139.57], EntityChicken['Chicken'/60, l='MpServer', x=1531.85, y=4.00, z=1156.24]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by bofrankbo** [comment]
Bug Fixed!
